FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install --omit=dev

FROM node:20-alpine
WORKDIR /app
COPY --from=builder /app/node_modules ./node_modules
COPY . .

RUN addgroup -g  1001 -S nodejs && \
    adduser -S nodejs -u 1001 &&\
    chown -R nodejs:nodejs /app

USER nodejs

EXPOSE 3000
CMD ["node", "src/server.js"]