apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: internal-devops-platform
  namespace: monitoring
spec:
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      observe: app
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
