apiVersion: v1
kind: ServiceAccount
metadata:
  name: release-deployer
  namespace: saas-dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: release-deployer
  namespace: saas-dev
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  - replicasets
  verbs:
  - get
  - list
  - watch
  - create
  - patch
  - update
- apiGroups:
  - ''
  resources:
  - services
  - pods
  verbs:
  - get
  - list
  - watch
  - create
  - patch
  - update
- apiGroups:
  - ''
  resources:
  - pods/exec
  verbs:
  - create
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - get
  - list
  - create
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: release-deployer
  namespace: saas-dev
subjects:
- kind: ServiceAccount
  name: release-deployer
  namespace: saas-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: release-deployer
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: release-deployer
  namespace: saas-staging
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: release-deployer
  namespace: saas-staging
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  - replicasets
  verbs:
  - get
  - list
  - watch
  - create
  - patch
  - update
- apiGroups:
  - ''
  resources:
  - services
  - pods
  verbs:
  - get
  - list
  - watch
  - create
  - patch
  - update
- apiGroups:
  - ''
  resources:
  - pods/exec
  verbs:
  - create
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - get
  - list
  - create
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: release-deployer
  namespace: saas-staging
subjects:
- kind: ServiceAccount
  name: release-deployer
  namespace: saas-staging
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: release-deployer
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: release-deployer
  namespace: saas-production
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: release-deployer
  namespace: saas-production
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  - replicasets
  verbs:
  - get
  - list
  - watch
  - create
  - patch
  - update
- apiGroups:
  - ''
  resources:
  - services
  - pods
  verbs:
  - get
  - list
  - watch
  - create
  - patch
  - update
- apiGroups:
  - ''
  resources:
  - pods/exec
  verbs:
  - create
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - get
  - list
  - create
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: release-deployer
  namespace: saas-production
subjects:
- kind: ServiceAccount
  name: release-deployer
  namespace: saas-production
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: release-deployer
